In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]],columns=['cgpa','resume_score','lpa'])

In [ ]:
df

cgpa  resume_score  lpa
0     8             8    4
1     7             9    5
2     6            10    6
3     5            12    7

In [ ]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [ ]:
model = Sequential()

In [ ]:
model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation='linear'))

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 6         
                                                                 
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9 (36.00 Byte)
Trainable params: 9 (36.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
#keras takes random values of weights
model.get_weights()

[array([[ 1.0296036 , -0.94074965],
        [-0.5137751 , -0.01993728]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 1.1530589 ],
        [-0.00681293]], dtype=float32),
 array([0.], dtype=float32)]

In [ ]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [ ]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values, epochs=100, verbose=1,batch_size=1)

Epoch 1/100
4/4 [==============================] - 1s 5ms/step - loss: 23.1119
Epoch 2/100
4/4 [==============================] - 0s 4ms/step - loss: 22.5415
Epoch 3/100
4/4 [==============================] - 0s 4ms/step - loss: 22.2054
Epoch 4/100
4/4 [==============================] - 0s 3ms/step - loss: 21.6589
Epoch 5/100
4/4 [==============================] - 0s 3ms/step - loss: 21.2366
Epoch 6/100
4/4 [==============================] - 0s 8ms/step - loss: 20.5265
Epoch 7/100
4/4 [==============================] - 0s 6ms/step - loss: 20.1650
Epoch 8/100
4/4 [==============================] - 0s 3ms/step - loss: 19.7322
Epoch 9/100
4/4 [==============================] - 0s 3ms/step - loss: 19.3474
Epoch 10/100
4/4 [==============================] - 0s 6ms/step - loss: 18.8333
Epoch 11/100
4/4 [==============================] - 0s 10ms/step - loss: 18.5566
Epoch 12/100
4/4 [==============================] - 0s 5ms/step - loss: 18.1116
Epoch 13/100
4/4 [==============================

In [ ]:
model.get_weights()

[array([[ 1.1130356, -1.0526938],
        [-0.3652937, -0.2312191]], dtype=float32),
 array([ 0.12439287, -0.17373681], dtype=float32),
 array([[ 1.0331889 ],
        [-0.11545045]], dtype=float32),
 array([0.12611344], dtype=float32)]